{{- if .Values.createServiceAccount -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name | quote }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Release.Name | quote }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
