name: Generate Chart Readme

on:
  pull_request:
    branches:
      - main
    paths:
      - 'chart/**/values.yaml'

jobs:
  generate-chart-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kungze/readme-generator-for-helm
        uses: actions/checkout@v2
        with:
          repository: 'kungze/readme-generator-for-helm'
          ref: 'kungze'
          path: readme-generator-for-helm

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('readme-generator-for-helm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install readme-generator-for-helm dependencies
        run: cd readme-generator-for-helm && npm install

      - name: Checkout reposigory
        uses: actions/checkout@v2
        with:
          path: ubuntu-develop-env

      - name: Execute readme-generator-for-helm
        run: readme-generator-for-helm/bin/index.js -v ubuntu-develop-env/chart/values.yaml -r ubuntu-develop-env/chart/README.md -s values.schema.json

      - name: Output generated README.md
        run: cat ubuntu-develop-env/chart/README.md

      - name: Output gererated values.schema.json
        run: cat values.schema.json
